#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_SIZE_STACK 100
#define MAX_SIZE_SCOPE 50
#define NUM_TYPES 13
#define MAX_LINES 1000
#define MAX_LINE_LEN 256
#define HASH_TABLE_SIZE 500
#define MAX_VAR_NAME 30

#endif