#include "helpers/test_helpers.h"

void test_semantic_accepts_builtin_print_functions(void);
void test_semantic_rejects_redeclaration_of_builtin_print_function(void);
void test_semantic_accepts_extern_function_declarations(void);
void test_semantic_rejects_duplicate_extern_function_declaration(void);
void test_semantic_rejects_conflict_between_extern_and_defined_function(void);
void test_semantic_validates_extern_function_argument_types(void);
void test_semantic_accepts_sized_array_argument_for_matching_parameter(void);
void test_lexer_tokenizes_logical_and_equality_operators(void);
void test_lexer_tokenizes_break_and_continue_keywords_together(void);
void test_lexer_tokenizes_extern_function_declaration(void);
void test_lexer_tokenizes_address_of_operator(void);
void test_parser_parses_extern_function_declaration(void);
void test_parser_rejects_extern_function_inside_block(void);
void test_parser_requires_func_after_extern(void);
void test_parser_parses_pointer_type_declaration(void);
void test_parser_parses_address_of_expression(void);
void test_parser_parses_dereference_expression(void);
void test_parser_accepts_dereference_assignment_target(void);
void test_semantic_accepts_logical_and_with_bool_operands(void);
void test_semantic_rejects_logical_and_with_non_bool_operand(void);
void test_semantic_accepts_logical_or_with_bool_operands(void);
void test_semantic_rejects_logical_or_with_non_bool_operand(void);
void test_semantic_accepts_equality_with_compatible_operands(void);
void test_semantic_rejects_equality_with_incompatible_operands(void);
void test_semantic_accepts_inequality_with_compatible_operands(void);
void test_semantic_rejects_inequality_with_incompatible_operands(void);
void test_semantic_accepts_unary_not_for_bool_operand(void);
void test_semantic_rejects_unary_not_for_non_bool_operand(void);
void test_semantic_rejects_array_literal_with_incompatible_element_types(void);
void test_semantic_accepts_nested_array_literal_with_matching_shapes(void);
void test_semantic_accepts_address_of_variable(void);
void test_semantic_accepts_dereference_read_and_write(void);
void test_semantic_rejects_address_of_non_lvalue(void);
void test_semantic_rejects_dereference_of_non_pointer(void);
void test_semantic_rejects_assignment_through_pointer_with_wrong_type(void);
void test_semantic_accepts_pointer_addition_with_int_offset(void);
void test_semantic_accepts_pointer_subtraction_with_int_offset(void);
void test_semantic_rejects_integer_plus_pointer(void);
void test_semantic_rejects_pointer_plus_pointer(void);
void test_semantic_rejects_pointer_minus_pointer(void);
void test_semantic_rejects_void_pointer_arithmetic(void);
void test_ir_builder_predeclares_builtin_runtime_functions(void);
void test_ir_printer_emits_runtime_function_declarations(void);
void test_ir_builder_registers_extern_function_symbols(void);
void test_ir_printer_emits_extern_function_declarations(void);
void test_ir_printer_does_not_define_extern_function_body(void);
void test_ir_printer_emits_float_values_as_double(void);
void test_ir_printer_emits_bool_values_as_i1(void);
void test_ir_printer_escapes_special_characters_in_string_literals(void);
void test_ir_printer_emits_sub_mul_and_div_operations(void);
void test_ir_printer_rejects_non_void_function_without_return_on_all_paths(void);
void test_ir_printer_writes_module_to_file(void);
void test_ir_printer_emits_missing_comparison_variants(void);
void test_ir_printer_emits_unary_negation_and_not(void);
void test_ir_printer_emits_logical_and_or(void);
void test_ir_printer_emits_multi_index_array_access(void);
void test_ir_printer_initializes_nested_array_literals_element_by_element(void);
void test_ir_printer_emits_break_and_continue_in_while(void);
void test_ir_printer_emits_break_and_continue_in_for(void);
void test_ir_printer_inferrs_unsized_array_length_from_literal(void);
void test_ir_printer_emits_load_through_pointer_dereference(void);
void test_ir_printer_emits_store_through_pointer_dereference(void);
void test_ir_printer_emits_gep_for_pointer_addition(void);
void test_ir_printer_emits_gep_for_pointer_subtraction(void);
void test_ir_printer_preserves_sized_array_parameter_types_in_calls(void);
void test_integration_emits_ir_for_globals_function_calls_and_control_flow(void);
void test_integration_emits_ir_for_single_dimension_array_access(void);
void test_integration_emits_ir_for_runtime_print_calls(void);

int test_failures = 0;
int tests_run = 0;
int tests_passed = 0;
int tests_failed = 0;

int main(void) {
    RUN_TEST(test_lexer_tokenizes_double_colon_and_types, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_tokenizes_keywords_and_assignments, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_fixture_basic_program, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_tokenizes_specific_delimiters, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_tracks_line_and_column, "tests/lexer/test_lexer.c");
    RUN_TEST(test_get_tokens_preserves_position_across_calls, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_struct_tracks_position_and_tokens, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_struct_preserves_scan_state, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_tokenizes_logical_and_equality_operators, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_tokenizes_break_and_continue_keywords_together, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_tokenizes_extern_function_declaration, "tests/lexer/test_lexer.c");
    RUN_TEST(test_lexer_tokenizes_address_of_operator, "tests/lexer/test_lexer.c");
    RUN_TEST(test_parser_parses_assignment_without_symbol_lookup, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_declaration_syntax_without_semantics, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_call_syntax_without_function_type, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_array_index_syntax_without_array_type, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_grouping_with_specific_delimiter_tokens, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_gives_and_higher_precedence_than_or, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_struct_parses_program_from_initialized_state, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_float_literals, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_copies_token_strings_into_ast, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_reports_syntax_error_at_eof_without_crashing, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_reports_specific_syntax_errors, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_reports_eof_errors_in_last_token_positions, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_reports_error_positions, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_rejects_invalid_assignment_targets, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_requires_explicit_function_return_type, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_function_return_types, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_empty_return_in_void_function, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_unary_minus_expression, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_break_and_continue_statements, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_rejects_assignment_at_file_scope, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_rejects_expression_statement_at_file_scope, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_rejects_if_at_file_scope, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_rejects_while_at_file_scope, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_rejects_for_at_file_scope, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_rejects_return_break_and_continue_at_file_scope, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_extern_function_declaration, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_rejects_extern_function_inside_block, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_requires_func_after_extern, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_pointer_type_declaration, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_address_of_expression, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_parses_dereference_expression, "tests/parser/test_parser.c");
    RUN_TEST(test_parser_accepts_dereference_assignment_target, "tests/parser/test_parser.c");
    RUN_TEST(test_semantic_starts_with_no_errors_for_empty_program, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_incompatible_initializer_types, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_duplicate_variable_in_same_scope, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_allows_shadowing_in_nested_scope, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_duplicate_function_in_global_scope, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_duplicate_parameter_name, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_undeclared_variable_use, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_invalid_arithmetic_types, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_non_boolean_condition, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_call_to_undeclared_function, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_builtin_print_functions, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_redeclaration_of_builtin_print_function, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_extern_function_declarations, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_duplicate_extern_function_declaration, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_conflict_between_extern_and_defined_function, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_validates_extern_function_argument_types, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_wrong_argument_count, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_wrong_argument_type, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_sized_array_argument_for_matching_parameter, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_non_integer_array_index, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_indexing_non_array_value, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_incompatible_assignment_through_array_access, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_assignment_through_nested_array_access, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accumulates_multiple_errors, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_initializing_int_with_void_call, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_non_void_function_without_return, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_non_void_function_with_if_missing_else_return, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_incompatible_function_return_type, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_value_return_inside_void_function, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_return_statement_outside_function, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_matching_function_return_type, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_if_else_when_both_branches_return, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_empty_return_inside_void_function, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_empty_return_inside_non_void_function, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_empty_return_outside_function, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_unreachable_code_after_returning_if_else, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_unary_minus_for_numeric_operand, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_break_outside_loop, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_reports_continue_outside_loop, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_literal_global_initializers, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_computed_global_initializer, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_identifier_global_initializer, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_break_and_continue_inside_while, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_break_and_continue_inside_for, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_logical_and_with_bool_operands, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_logical_and_with_non_bool_operand, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_logical_or_with_bool_operands, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_logical_or_with_non_bool_operand, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_equality_with_compatible_operands, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_equality_with_incompatible_operands, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_inequality_with_compatible_operands, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_inequality_with_incompatible_operands, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_unary_not_for_bool_operand, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_unary_not_for_non_bool_operand, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_array_literal_with_incompatible_element_types, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_nested_array_literal_with_matching_shapes, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_address_of_variable, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_dereference_read_and_write, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_address_of_non_lvalue, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_dereference_of_non_pointer, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_assignment_through_pointer_with_wrong_type, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_pointer_addition_with_int_offset, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_accepts_pointer_subtraction_with_int_offset, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_integer_plus_pointer, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_pointer_plus_pointer, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_pointer_minus_pointer, "tests/semantic/test_semantic.c");
    RUN_TEST(test_semantic_rejects_void_pointer_arithmetic, "tests/semantic/test_semantic.c");
    RUN_TEST(test_tokenize_file_appends_single_eof_for_multiline_input, "tests/integration/test_integration.c");
    RUN_TEST(test_integration_parses_input_program_ast, "tests/integration/test_integration.c");
    RUN_TEST(test_integration_parses_loop_control_and_unary_ast, "tests/integration/test_integration.c");
    RUN_TEST(test_integration_emits_ir_for_globals_function_calls_and_control_flow, "tests/integration/test_integration.c");
    RUN_TEST(test_integration_emits_ir_for_single_dimension_array_access, "tests/integration/test_integration.c");
    RUN_TEST(test_integration_emits_ir_for_runtime_print_calls, "tests/integration/test_integration.c");
    RUN_TEST(test_ir_builder_creates_module_for_empty_program, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_builder_predeclares_global_and_function_symbols, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_private_string_global, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_add_and_return, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_lowers_compound_assignment_through_load_compute_store, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_conditional_branches_and_labels, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_gep_for_array_access, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_function_call, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_preserves_sized_array_parameter_types_in_calls, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_builder_predeclares_builtin_runtime_functions, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_runtime_function_declarations, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_builder_registers_extern_function_symbols, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_extern_function_declarations, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_does_not_define_extern_function_body, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_loop_comparisons_and_branches, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_reads_and_writes_global_variables, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_float_values_as_double, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_bool_values_as_i1, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_escapes_special_characters_in_string_literals, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_sub_mul_and_div_operations, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_rejects_non_void_function_without_return_on_all_paths, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_writes_module_to_file, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_missing_comparison_variants, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_unary_negation_and_not, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_logical_and_or, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_multi_index_array_access, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_initializes_nested_array_literals_element_by_element, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_break_and_continue_in_while, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_break_and_continue_in_for, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_inferrs_unsized_array_length_from_literal, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_load_through_pointer_dereference, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_store_through_pointer_dereference, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_gep_for_pointer_addition, "tests/ir/test_ir.c");
    RUN_TEST(test_ir_printer_emits_gep_for_pointer_subtraction, "tests/ir/test_ir.c");

    printf("\n");
    printf("Tests run: %d\n", tests_run);
    printf(TEST_COLOR_GREEN "Passed: %d\n" TEST_COLOR_RESET, tests_passed);
    if (tests_failed != 0) {
        printf(TEST_COLOR_RED "Failed: %d\n" TEST_COLOR_RESET, tests_failed);
    } else {
        printf(TEST_COLOR_GREEN "Failed: %d\n" TEST_COLOR_RESET, tests_failed);
    }

    if (test_failures != 0) {
        fprintf(stderr, TEST_COLOR_RED "%d assertions failed\n" TEST_COLOR_RESET, test_failures);
        return 1;
    }

    printf(TEST_COLOR_GREEN "all tests passed\n" TEST_COLOR_RESET);
    return 0;
}
